name: Publish Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
  pull-requests: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish --access=public
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          username: octopusdeploy
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          context: .
          push: true
          tags: octopusdeploy/mcp-server:latest,octopusdeploy/mcp-server:${{ steps.release.outputs.tag_name }}
